job:
  name: ztp-dayn-job
  image:
    repository: 657273346644.dkr.ecr.us-east-1.amazonaws.com/hpe-hcss/ztp-dayn-image:v0.0.1-register
  numberOfNodes: "2"

store_info:
  store_id: ST0777
  store_json: ST0777.json