# templates/job.yaml

apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Values.job.name }}

spec:
  template:
    spec:
      containers:
      - name: {{ .Values.job.name }}
        image: {{ .Values.job.image.repository }}
        command: ["python3", "ZTP/tpm_backup.py", "{{ .Values.store_info.store_json }}" ] 
      restartPolicy: Never